artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: "https://drive.google.com/file/d/1ucuX5BjM-DBkSRfhMooyUqW3A7PixUZ3/view?usp=sharing"
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion
  